server:
  port: 8888

spring:
  application:
    name: msvc-configServer
  cloud:
    config:
      server:
        bootstrap: false
       # native:
        #  search-locations: classpath:/config # Indica que use archivos locales en el directorio /config dentro del classpath
        git:
          uri: https://github.com/jsFacled/dmh-configServer-repo.git

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Configuración por defecto para local
    register-with-eureka: true
    fetch-registry: true

---
# Configuración para Docker
#spring:
  #profiles: dev

# A partir de springboot 3 cambian las marcas para perfiles
spring:
  config:
    activate:
      on-profile: dev

eureka:
  client:
    service-url:
      defaultZone: http://msvc-eureka:8761/eureka/  # Configuración para Docker, usa el nombre del servicio
    register-with-eureka: true
    fetch-registry: true
