server:
  port: 8888

spring:
  application:
    name: msvc-configServer
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config
          
        bootstrap: false
       # native:
        #  search-locations: classpath:/config # Indica que use archivos locales en el directorio /config dentro del classpath
        git:
          uri: https://github.com/jsFacled/dmh-configServer-repo.git

logging:
  level:
    org.springframework.cloud.config: DEBUG

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
