server:
  port: 8888

spring:
  application:
    name: msvc-configServer
  cloud:
    config:
      server:
        bootstrap: false
       # native:
        #  search-locations: classpath:/config # Indica que use archivos locales en el directorio /config dentro del classpath
        git:
          uri: https://github.com/jsFacled/dmh-configServer-repo.git


eureka:
  client:
    service-url:
      defaultZone: http://msvc-eureka:8761/eureka/  # Cambia 'localhost' por el nombre del servicio en Docker
    register-with-eureka: true
    fetch-registry: true