spring:
  application:
    name: msvc-users



# Configuraciones específicas del perfil "local"
---
spring:
  config:
    activate:
      on-profile: local

    import: optional:configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Dirección local de Eureka
    register-with-eureka: true
    fetch-registry: true

---
# Configuración para Docker
#spring:
  #profiles: dev

# A partir de springboot 3 cambian las marcas para perfiles
spring:
  config:
    activate:
      on-profile: dev

eureka:
  client:
    service-url:
      defaultZone: http://msvc-eureka:8761/eureka/  # Configuración para Docker, usa el nombre del servicio
    register-with-eureka: true
    fetch-registry: true
