spring:
  application:
    name: msvc-users
  config:
    import: optional:configserver:http://localhost:8888

  profiles:
    active: "local"


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: INFO
    com.tu.paquete: DEBUG  # Reemplaza esto con el paquete base de tu aplicación