spring:
  application:
    name: msvc-eureka
  

  cloud:
    config:
      enabled: false
      
server:
  port: 8761 # Configuración del puerto en el que correrá Eureka Server

eureka:
  server:
    # Configuraciones específicas del servidor Eureka
    enable-self-preservation: false # Opcional, para deshabilitar la preservación automática
    eviction-interval-timer-in-ms: 5000 # Opcional, intervalo de limpieza de instancias en milisegundos

  client:
    register-with-eureka: false # El servidor Eureka no necesita registrarse a sí mismo
    fetch-registry: false # El servidor Eureka no necesita obtener el registro de otros servicios
    
