spring:
  application:
    name: msvc-eureka
  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    config:
      enabled: true
      
server:
  port: 8761 # Configuración del puerto en el que correrá Eureka Server
