spring:
  profiles:
    active: "local"

  application:
    name: msvc-cards
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      uri: http://localhost:8888  #where the config-service is running
      fail-fast: true             #the service will not run if it can't reach the config-service
      import-check:
        enabled: false              #anula la importación de configuración

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
