spring:
  application:
    name: msvc-transactions

  config:
    import: optional:configserver:http://localhost:8888

  profiles:
    active: "local"



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

