spring:
  application:
    name: msvc-transactions

  config:
    import: optional:configserver:http://localhost:8888

  profiles:
    active: local



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
