server:
  port: 8081

spring:
  application:
    name: msvc-usersAccountsManager
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: "local"
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: msvc-configServer

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true


      #serviceUrl:
      #defaultZone: http://localhost:8761/eureka/
