server:
  port: 8081

spring:
  application:
    name: msvc-usersAccountsManager
  config:
    import: configserver:http://localhost:8888/msvc-usersAccountsManager-local.yml
  #profiles:
    #active: "local"


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761

